services:
  - type: web
    name: rifas-backoffice
    env: static
    buildCommand: cd rifas-backoffice && npm install && npm run build
    staticPublishPath: ./rifas-backoffice/dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false

